### ISSUE TITLE
trouble creating a transaction

### ISSUE THREAD

**Issue by hanshaueter** [moneybutton/bsv#94]
Hi there, I'm quite new to JS and BSV programming. I tried to create a raw transaction, but I wasn't very successful. 
I installed the bsv library "npm install --save --save-exact bsv" and ran the following code: 

`let bsv = require('bsv');

let str_privateKey = 'L5aw273pEhyQBJQCZXjg42QqkaLnTGSdpDNmRD6eCTNXFqu5EsJ9';
let privateKey2 = bsv.PrivateKey.fromWIF(str_privateKey)

var tx = bsv.Transaction();
    tx.from('0200000001c3203f4bbe59399b343103f1368f9e27e248f75a8e0ac166deadca1a41cf7506000000006a47304402200c146b37ac8a1ff971db6992c0190e24caad2080d6e1dcd120457c61b27d20e802205dd28518744cfe0b7791024efaa3ef2d870b29a66a6a0737a191a4772b7518a9412102394c63c0ee8c2efc9cbb771c6d704323b62e6014ce19a18caee4ad9858903e5affffffff02e8060100000000001976a914f51cc15ce74136ed6371af8d03f1c9ecfabd219e88ace387a80d000000001976a914318ea8397710273b3255353723cfe036f56542a688ac00000000');          // _I used the transaction hex (not sure if this is right_
    tx.to('1718koF1VRrNg5ADLQLRMLHomTwYekEGTE', '65304');  // Added an address and an output in satoshis (basically, the full amount minus 2000 satoshis)
    tx.change('1718koF1VRrNg5ADLQLRMLHomTwYekEGTE');      // Sets up a change address where the rest of the funds will go
    tx.sign(privateKey2);     // Signs all the inputs it can

const serializedTx = tx.serialize();
  console.log(serializedTx);`

However, it's not working. Any input is welcome! thank you for the support.

**Comment by bitcartel** [comment]
The following code should work:
```
var tx = new bsv.Transaction('0200000001c3203f4bbe59399b343103f1368f9e27e248f75a8e0ac166deadca1a41cf7506000000006a47304402200c146b37ac8a1ff971db6992c0190e24caad2080d6e1dcd120457c61b27d20e802205dd28518744cfe0b7791024efaa3ef2d870b29a66a6a0737a191a4772b7518a9412102394c63c0ee8c2efc9cbb771c6d704323b62e6014ce19a18caee4ad9858903e5affffffff02e8060100000000001976a914f51cc15ce74136ed6371af8d03f1c9ecfabd219e88ace387a80d000000001976a914318ea8397710273b3255353723cfe036f56542a688ac00000000') // I used the transaction hex (not sure if this is right
    .to('1718koF1VRrNg5ADLQLRMLHomTwYekEGTE', 65304) // Added an address and an output in satoshis (basically, the full amount minus 2000 satoshis)
    .change('1718koF1VRrNg5ADLQLRMLHomTwYekEGTE') // Sets up a change address where the rest of the funds will go
    .sign(privateKey2); // Signs all the inputs it can
```

However, there will be a failure when calling `change()`:

```Abstract Method Invocation: Input#clearSignatures```

It seems that when you deserialize a transaction, the reader will instantiate Input objects as part of the Transaction object (https://github.com/moneybutton/bsv/blob/master/lib/transaction/transaction.js#L297), but not the specific subclass of Input (https://github.com/moneybutton/bsv/blob/master/lib/transaction/input/input.js#L99).

This is a problem because in order to clear signatures you need to have a subclass which has the method implemented, as the base class does not implement it (https://github.com/moneybutton/bsv/blob/master/lib/transaction/input/input.js#L175).

The code is also not implemented in upstream (https://github.com/bitpay/bitcore-lib/blob/master/lib/transaction/input/input.js#L98).

**Comment by ryanxcharles** [comment]
This is obsolete for bsv 2.0.
